- task: Maven@4
- task: GitHubComment@0
  inputs:
    gitHubConnection: 'GitHub - LucasBrito162'
    repositoryName: 'LucasBrito162/bugbank'
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Primeiro'
    codeCoverageToolOption: 'Cobertura'
    codeCoverageFailIfEmpty: true
    codeCoverageRestoreOriginalPomXml: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false