name: Java Selenium Maven Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Cópia repositório executor
        uses: actions/checkout@v3

      - name: Configurar JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'adopt'
          cache: maven

      - name: Dependências Maven
        run: |
          mvn --batch-mode --update-snapshots package

      - name: Iniciar o Chrome
        run: |
          choco install chromium
          choco install chromedriver

      - name: Build with Maven
        run: |
          mvn clean install
          mvn test
          exit 0

      - name: Gerar Relatório
        run: |
          mkdir allure-result
          mvn allure:report
          

      - name: Publicar relatório do Allure como artefato
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
                    
          
          
          
          
          
          
          

          
