name: Java Selenium Maven Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Cópia repositório executor
        uses: actions/checkout@v3

      - name: Configurar JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'adopt'
          cache: maven

      - name: Dependências Maven
        run: |
          mvn --batch-mode --update-snapshots package

      - name: Iniciar o Chrome
        run: |
          choco install chromium
          choco install chromedriver

      - name: Build with Maven
        run: |
          mvn install
          mvn test
          exit 0

      - name: Gerar JUnit report
        run: mvn surefire-report:report

      - name: Copiar JUnit report para o diretório de artefatos
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          cp -R target ${{ github.workspace }}/artifacts

      - name: Upload do JUnit report
        uses: actions/upload-artifact@v2
        with:
          name: JUnit-Report
          path: ${{ github.workspace }}/artifacts

  deploy:
    needs: [build]
    runs-on: windows-latest
    steps:
      - name: Copiar artefato para o diretório de publicação
        run: |
          mkdir public
          cp -r ${{ github.workspace }}/target/surefire-reports public/

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
